apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: create-sqs-template
  description: Criação de uma fila SQS com Terraform
spec:
  owner: anotaai-infrastructure
  type: service
  templater: go-template  # Usando Go-Template para geração
  path: ./templates/create-sqs
  parameters:
    - title: Nome da Fila
      description: O nome da fila SQS
      type: string
      required: true
    - title: Tempo de Retenção
      description: Tempo de retenção da fila (em segundos)
      type: integer
      default: 345600
    - title: Política de Visibilidade
      description: Tempo de visibilidade da fila (em segundos)
      type: integer
      default: 30
  steps:
    - id: generate-sqs
      name: Gerar arquivo Terraform para SQS
      action: scaffolder:template
      input:
        template: ./templates/create-sqs
        parameters:
          sqsName: "{{parameters.title}}"
          retention: "{{parameters.retentionTime}}"
          visibilityTimeout: "{{parameters.visibilityTimeout}}"
